### ISSUE TITLE
Prevent BloodHound

### ISSUE THREAD

**Issue by CG-root** [PaulSec/awesome-windows-domain-hardening#14]
It would be great if you can add the following to prevent execution of BloodHound tool:

1. Use [NetCease ](https://gallery.technet.microsoft.com/Net-Cease-Blocking-Net-1e8dcb5b) to prevent unprivileged session enumeration.
2. Use [Samri10 ](https://gallery.technet.microsoft.com/SAMRi10-Hardening-Remote-48d94b5b) to prevent unprivileged local admin collection (this fix already exists in Windows 10 1607 and above).

**Comment by jokezone** [comment]
Did you mean prevent execution or prevent anonymous enumeration of logged on users? Has anyone successfully implemented these scripts in large production environments? There seems to be a lot of quirky issues reported after using them. Instead, our organisation restricts the log on over the network right to administrator group members and denies anonymous enumeration of the SAM database. That was enough to stop bloodhound from enumerating logged on users. Please correct me if I'm overlooking anything.

**Comment by PaulSec** [comment]
I've haven't any any big issue to run this in several big environment (80k users, 90k+ workstations, .. )

**Comment by PaulSec** [comment]
Thanks a lot for those inputs!

on an other topics, I haven't had any issue to run BloodHound (in my case SharpHound ingestor) in large production environments, this was pretty stable for me and what I mean by large env is roughly ~80k users with the `All` CollectionMethod.
