### ISSUE TITLE
Hardening against DMA attacks

### ISSUE THREAD

**Issue by Genbox** [PaulSec/awesome-windows-domain-hardening#3]
Due to driver loading happening on-the-fly when devices are inserted, an attacker can insert DMA based devices and extract hard drive and memory content. 

[Article by Microsoft](https://support.microsoft.com/en-us/help/2516445/blocking-the-sbp-2-driver-and-thunderbolt-controllers-to-reduce-1394-dma-and-thunderbolt-dma-threats-to-bitlocker)

**Comment by PaulSec** [comment]
@gepeto42 any idea in which section we should add this? Initial foothold?

**Comment by Atavic** [comment]
Initial Foothold section lists Applocker. This technology has variables, for removable drive and storage, that can be used for rules that prevent installs from removable devices.

See: [AppLocker Design Guide](http://docshare02.docshare.tips/files/17344/173447840.pdf) Section 2.4.4
