### ISSUE TITLE
Use PingCastle ?

### ISSUE THREAD

**Issue by vletoux** [PaulSec/awesome-windows-domain-hardening#6]
Just a remark.
I tried to do a checklist but become complicated quite fast.
Example: by default any user can add up to 10 computers to the domain => set ms-DS-MachineAccountQuota = 0
Check for trusts SID Filtering
Passwords in GPP or the DC object ownership:
`Get-ADComputer -server my.domain.to.check -LDAPFilter "(&(objectCategory=computer)(|(primarygroupid=521)(primarygroupid=516)))" -properties name, ntsecuritydescriptor | select name,{$_.ntsecuritydescriptor.Owner}`
(should be domain admin or entreprise admin)
=> I automatize many checks in the PingCastle tool (https://www.pingcastle.com) and made further steps.
Do not hesitate to come back to me - note: check my previous work in the attack field
Vincent

**Comment by PaulSec** [comment]
Bon, ça aura pris du temps mais je t'ai intégré dans la liste. 

A bientôt et désolé pour le retard 🍺
