### ISSUE TITLE
Link to "Explaining and adapting Tay’s Sysmon configuration" is dead

### ISSUE THREAD

**Issue by rakanskiy** [PaulSec/awesome-windows-domain-hardening#8]

**Comment by Atavic** [comment]
[Waybackmachine](http://web.archive.org/web/20170531120041/https://medium.com/@lennartkoopmann/explaining-and-adapting-tays-sysmon-configuration-27d9719a89a8) and

https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml have it all.

The broken media links are SwiftOnSecurity tweets.

**Comment by Atavic** [comment]
[Waybackmachine](http://web.archive.org/web/20170531120041/https://medium.com/@lennartkoopmann/explaining-and-adapting-tays-sysmon-configuration-27d9719a89a8) and [sysmon-config](https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml) have it all. The broken media links are SwiftOnSecurity tweets.
